//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserFittingAndAccessoryCalculationServers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserFittingAndAccessoryCalculationServers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 5.0.0 of the User duct fitting database has been implemented for duct fittings, when using the method, the duct fitting coefficient will be read from mapped User table..
        /// </summary>
        internal static string DuctUserTablePressureDropServerDescription {
            get {
                return ResourceManager.GetString("DuctUserTablePressureDropServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://wiki.autodesk.com/display/aeceng/MEP2-109.
        /// </summary>
        internal static string DuctUserTablePressureDropServerInformationLink {
            get {
                return ResourceManager.GetString("DuctUserTablePressureDropServerInformationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Coefficient from User Table.
        /// </summary>
        internal static string DuctUserTablePressureDropServerName {
            get {
                return ResourceManager.GetString("DuctUserTablePressureDropServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIBSE/User/Crane standards are used to pipe fitting loss definition based on the pipe fitting types..
        /// </summary>
        internal static string PipeKFactorTablePressureDropServerDescription {
            get {
                return ResourceManager.GetString("PipeKFactorTablePressureDropServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://wiki.autodesk.com/display/aeceng/MEP2-109.
        /// </summary>
        internal static string PipeKFactorTablePressureDropServerInformationLink {
            get {
                return ResourceManager.GetString("PipeKFactorTablePressureDropServerInformationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User K Coefficient from Table.
        /// </summary>
        internal static string PipeKFactorTablePressureDropServerName {
            get {
                return ResourceManager.GetString("PipeKFactorTablePressureDropServerName", resourceCulture);
            }
        }
    }
}
