//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserFittingAndAccessoryCalculationUIServers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserFittingAndAccessoryCalculationUIServers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revit-User.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Duct coefficient from table pressure drop UI server.
        /// </summary>
        internal static string DuctCoefficientFromTablePressureDropUIServerDescription {
            get {
                return ResourceManager.GetString("DuctCoefficientFromTablePressureDropUIServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Duct coefficient from table pressure drop UI server.
        /// </summary>
        internal static string DuctCoefficientFromTablePressureDropUIServerName {
            get {
                return ResourceManager.GetString("DuctCoefficientFromTablePressureDropUIServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input.
        /// </summary>
        internal static string InvalidInputMsg {
            get {
                return ResourceManager.GetString("InvalidInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K Coefficient:.
        /// </summary>
        internal static string KCoefficientLabel {
            get {
                return ResourceManager.GetString("KCoefficientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K Coefficient Table:.
        /// </summary>
        internal static string KFactorTableLabel {
            get {
                return ResourceManager.GetString("KFactorTableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Loss Coefficient:.
        /// </summary>
        internal static string LossCoefficientLabel {
            get {
                return ResourceManager.GetString("LossCoefficientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Pipe K coefficient from table pressure drop UI server.
        /// </summary>
        internal static string PipeKFactorFromTablePressureDropUIServerDescription {
            get {
                return ResourceManager.GetString("PipeKFactorFromTablePressureDropUIServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Pipe K coefficient from table pressure drop UI server.
        /// </summary>
        internal static string PipeKFactorFromTablePressureDropUIServerName {
            get {
                return ResourceManager.GetString("PipeKFactorFromTablePressureDropUIServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Table:.
        /// </summary>
        internal static string UserTableLabel {
            get {
                return ResourceManager.GetString("UserTableLabel", resourceCulture);
            }
        }
    }
}
