//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserPressureLossReport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserPressureLossReport.ReportResource", typeof(ReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Terminal.
        /// </summary>
        internal static string airTerminals {
            get {
                return ResourceManager.GetString("airTerminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t create a report because none of selected systems has the calculation option set to All..
        /// </summary>
        internal static string allItemsCaculationOff {
            get {
                return ResourceManager.GetString("allItemsCaculationOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Methods.
        /// </summary>
        internal static string calMethods {
            get {
                return ResourceManager.GetString("calMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the file.
        /// </summary>
        internal static string CanotOpen {
            get {
                return ResourceManager.GetString("CanotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Path.
        /// </summary>
        internal static string criticalPath {
            get {
                return ResourceManager.GetString("criticalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV (*.csv).
        /// </summary>
        internal static string csvFileFormat {
            get {
                return ResourceManager.GetString("csvFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate CSV Report.
        /// </summary>
        internal static string csvGenerateTitle {
            get {
                return ResourceManager.GetString("csvGenerateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate CSV report.
        /// </summary>
        internal static string csvMsg {
            get {
                return ResourceManager.GetString("csvMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close “%FULLPATH%” and try generating this file again..
        /// </summary>
        internal static string csvSubMsg {
            get {
                return ResourceManager.GetString("csvSubMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the report format?.
        /// </summary>
        internal static string deleteFormatMsg {
            get {
                return ResourceManager.GetString("deleteFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Report Format.
        /// </summary>
        internal static string deleteFormatTitle {
            get {
                return ResourceManager.GetString("deleteFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t delete this report format.
        /// </summary>
        internal static string deleteLastFormatMsg {
            get {
                return ResourceManager.GetString("deleteLastFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one format is required in a report..
        /// </summary>
        internal static string deleteLastFormatSubMsg {
            get {
                return ResourceManager.GetString("deleteLastFormatSubMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duct.
        /// </summary>
        internal static string ductDomain {
            get {
                return ResourceManager.GetString("ductDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duct Pressure Loss Report.
        /// </summary>
        internal static string ductReportName {
            get {
                return ResourceManager.GetString("ductReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duct Pressure Loss Report Settings.
        /// </summary>
        internal static string ductSettingsDlgTitle {
            get {
                return ResourceManager.GetString("ductSettingsDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duct Pressure Loss Report - System Selector.
        /// </summary>
        internal static string ductSystemSelectorDlgTitle {
            get {
                return ResourceManager.GetString("ductSystemSelectorDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duct Pressure Loss Report - System Type Filter.
        /// </summary>
        internal static string ductSystemTypeFilterDlgTitle {
            get {
                return ResourceManager.GetString("ductSystemTypeFilterDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        internal static string elementFiled {
            get {
                return ResourceManager.GetString("elementFiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element ID.
        /// </summary>
        internal static string elementId {
            get {
                return ResourceManager.GetString("elementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string equipments {
            get {
                return ResourceManager.GetString("equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitting and Accessory Loss Coefficient Summary by Sections.
        /// </summary>
        internal static string fittingDetailInfo {
            get {
                return ResourceManager.GetString("fittingDetailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fittings.
        /// </summary>
        internal static string fittings {
            get {
                return ResourceManager.GetString("fittings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitting and Accessory Loss Settings.
        /// </summary>
        internal static string fittingSettings {
            get {
                return ResourceManager.GetString("fittingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;default&gt;.
        /// </summary>
        internal static string formatDefaultName {
            get {
                return ResourceManager.GetString("formatDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format already exists. Do you want to override it?.
        /// </summary>
        internal static string formatNameDuplicateMsg {
            get {
                return ResourceManager.GetString("formatNameDuplicateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report format name can’t be empty.
        /// </summary>
        internal static string formatNameMsg {
            get {
                return ResourceManager.GetString("formatNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate HTML Report.
        /// </summary>
        internal static string htmlGenerateTitle {
            get {
                return ResourceManager.GetString("htmlGenerateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate HTML report..
        /// </summary>
        internal static string htmlMsg {
            get {
                return ResourceManager.GetString("htmlMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid System(s).
        /// </summary>
        internal static string invalidSystemMsg {
            get {
                return ResourceManager.GetString("invalidSystemMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value.
        /// </summary>
        internal static string invalidValueMsg {
            get {
                return ResourceManager.GetString("invalidValueMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string length {
            get {
                return ResourceManager.GetString("length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of selected systems have the calculation option set not to All.  Do you want to create a report for the rest of systems?.
        /// </summary>
        internal static string partOfItemsCaculationOff {
            get {
                return ResourceManager.GetString("partOfItemsCaculationOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe.
        /// </summary>
        internal static string pipeDomain {
            get {
                return ResourceManager.GetString("pipeDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Pipe Pressure Loss Report.
        /// </summary>
        internal static string pipeReportName {
            get {
                return ResourceManager.GetString("pipeReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Pipe Pressure Loss Report Settings.
        /// </summary>
        internal static string pipeSettingsDlgTitle {
            get {
                return ResourceManager.GetString("pipeSettingsDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Pipe Pressure Loss Report - System Selector.
        /// </summary>
        internal static string pipeSystemSelectorDlgTitle {
            get {
                return ResourceManager.GetString("pipeSystemSelectorDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Pipe Pressure Loss Report - System Type Filter.
        /// </summary>
        internal static string pipeSystemTypeFilterDlgTitle {
            get {
                return ResourceManager.GetString("pipeSystemTypeFilterDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure Loss Report Settings.
        /// </summary>
        internal static string plrSettings {
            get {
                return ResourceManager.GetString("plrSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plumbing Fixture.
        /// </summary>
        internal static string plumbingFixtures {
            get {
                return ResourceManager.GetString("plumbingFixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure Loss.
        /// </summary>
        internal static string pressureLoss {
            get {
                return ResourceManager.GetString("pressureLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure Loss Report.
        /// </summary>
        internal static string reportName {
            get {
                return ResourceManager.GetString("reportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Time.
        /// </summary>
        internal static string runTime {
            get {
                return ResourceManager.GetString("runTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string section {
            get {
                return ResourceManager.GetString("section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Pressure Loss.
        /// </summary>
        internal static string sectionPressureLoss {
            get {
                return ResourceManager.GetString("sectionPressureLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pressure Loss Calculations by Sections.
        /// </summary>
        internal static string sectionTitle {
            get {
                return ResourceManager.GetString("sectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Information of Straight Segment by Sections.
        /// </summary>
        internal static string segmentDetailInfo {
            get {
                return ResourceManager.GetString("segmentDetailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure Loss of .
        /// </summary>
        internal static string segmentMethods {
            get {
                return ResourceManager.GetString("segmentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Segment Settings.
        /// </summary>
        internal static string segmentSettings {
            get {
                return ResourceManager.GetString("segmentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No system is selected to create report..
        /// </summary>
        internal static string selectSystemsMsg {
            get {
                return ResourceManager.GetString("selectSystemsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        internal static string systemInformation {
            get {
                return ResourceManager.GetString("systemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pressure Loss.
        /// </summary>
        internal static string totalPressureLoss {
            get {
                return ResourceManager.GetString("totalPressureLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revit.
        /// </summary>
        internal static string warningTitle {
            get {
                return ResourceManager.GetString("warningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Page (*.html).
        /// </summary>
        internal static string webPageFileFormat {
            get {
                return ResourceManager.GetString("webPageFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t generate HTML file due to system file missing.
        /// </summary>
        internal static string xsltFileMsg {
            get {
                return ResourceManager.GetString("xsltFileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file %FULLPATH% can’t be found..
        /// </summary>
        internal static string xsltFileSubMsg {
            get {
                return ResourceManager.GetString("xsltFileSubMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
