//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserStraightSegmentCalculationServers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserStraightSegmentCalculationServers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDarcy.
        /// </summary>
        internal static string DuctPressureDropMethodName {
            get {
                return ResourceManager.GetString("DuctPressureDropMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Calculation of duct pressure drop using Darcy method..
        /// </summary>
        internal static string DuctPressureDropServerDescription {
            get {
                return ResourceManager.GetString("DuctPressureDropServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1033\deflangfe2052\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
        ///{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f4\fbidi \fswiss [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DuctPressureDropServerDescriptionRTF {
            get {
                return ResourceManager.GetString("DuctPressureDropServerDescriptionRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://wiki.autodesk.com/display/aeceng/MEP2-109.
        /// </summary>
        internal static string DuctPressureDropServerInformationLink {
            get {
                return ResourceManager.GetString("DuctPressureDropServerInformationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Duct Pressure Drop.
        /// </summary>
        internal static string DuctPressureDropServerName {
            get {
                return ResourceManager.GetString("DuctPressureDropServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDarcy-Weisbach.
        /// </summary>
        internal static string PipePressureDropMethodName {
            get {
                return ResourceManager.GetString("PipePressureDropMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Calculation of pressure drop using Darcy-Weisbach method..
        /// </summary>
        internal static string PipePressureDropServerDescription {
            get {
                return ResourceManager.GetString("PipePressureDropServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1033\deflangfe2052\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}
        ///{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f4\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Helvetica;}{\f10\fbidi \f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PipePressureDropServerDescriptionRTF {
            get {
                return ResourceManager.GetString("PipePressureDropServerDescriptionRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://wiki.autodesk.com/display/aeceng/MEP2-109.
        /// </summary>
        internal static string PipePressureDropServerInformationLink {
            get {
                return ResourceManager.GetString("PipePressureDropServerInformationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Pipe Pressure Drop.
        /// </summary>
        internal static string PipePressureDropServerName {
            get {
                return ResourceManager.GetString("PipePressureDropServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Plumbing Fixture Flow.
        /// </summary>
        internal static string PlumbingFixtureFlowMethodName {
            get {
                return ResourceManager.GetString("PlumbingFixtureFlowMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Calculation of flow using the Plumbing Fixture Flow method..
        /// </summary>
        internal static string PlumbingFixtureFlowServerDescription {
            get {
                return ResourceManager.GetString("PlumbingFixtureFlowServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1033\deflangfe2052\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}
        ///{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f4\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Helvetica;}{\f10\fbidi \f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlumbingFixtureFlowServerDescriptionRTF {
            get {
                return ResourceManager.GetString("PlumbingFixtureFlowServerDescriptionRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://wiki.autodesk.com/display/aeceng/MEP2-109.
        /// </summary>
        internal static string PlumbingFixtureFlowServerInformationLink {
            get {
                return ResourceManager.GetString("PlumbingFixtureFlowServerInformationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Plumbing Fixture Flow.
        /// </summary>
        internal static string PlumbingFixtureFlowServerName {
            get {
                return ResourceManager.GetString("PlumbingFixtureFlowServerName", resourceCulture);
            }
        }
    }
}
